controller_list:
  - name: fake_arm_planning_group_controller
    type: $(arg execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_gripper_planning_group_controller
    type: $(arg execution_type)
    joints:
      - gripper_joint_1
      - gripper_joint_2
initial:  # Define initial robot poses.
  - group: arm_planning_group
    pose: rest
  - group: gripper_planning_group
    pose: gripper_close